:memo: Add introduction to memory. Closes #2, Closes #3.
dipzza/ultrastar-song2txt pull request #4
Opened 2022-04-19 19:41 UTC by dipzza

2022-04-20 16:00 UTC, JJ commented
1. *Closes* don't work if included in the title.
2. You need to say *why* they close anything at all.

2022-04-20 17:58 UTC, JJ requested changes
La mayoría no son cambios en el propio texto, sino issues en el repo, pero con todo y con eso sería interesante que los hicieras antes de fusionar.

2022-04-20 17:58 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\section{Estado del Arte}
No uses Mayúsculas arbitrarias.

2022-04-20 17:58 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Automatizar los siguientes procesos
Todos estos objetivos deben estar en historias de usuario.

2022-04-26 12:09 UTC, JJ requested changes
Bastante bien como primera aproximación, dale una vuelta, por favor.

2022-04-26 12:09 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\section{Estado del arte}
En general, esto suele recibir un capítulo entero. No sólo en el problema en sí, sino en las herramientas que se usan. Pero puede valer como primera versión.

2022-04-26 12:09 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +	\item Detecta automáticamente el BPM de la canción
Defínelo

2022-04-26 12:09 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +
Al final del estado del arte tendrás que decir en qué pretendes ir más allá. 
También deberías de incluir soluciones privativas, o incluso trabajos de investigación (si los hubiera) que fueran relevantes. Otras bibliotecas que hagan parte, en fin, todo lo que conozcas.

2022-04-26 12:09 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +		\item Pulsaciones por minuto
¿BPM es esto?

2022-04-26 12:09 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\textbf{Facilitar la asignación de tonos}. Al ser la parte que más tiempo consume y que requiere mayor nivel de habilidad reducir la complejidad de este proceso supondría un importante beneficio.
Esto sería un subobjetivo, la verdad, o uno de los productos mínimamente viables. El objetivo debería ser más general. NO pasa nada si no lo vas a alcanzar siempre que puedas decir que has contribuido o avanzado hacia él.

2022-04-29 21:06 UTC, dipzza commented on doc/secciones/01_introduccion.tex
> +\section{Estado del arte}
Si te parece bien voy a dejar por ahora lo de estado del arte así y más tarde veo donde lo muevo.

Me parecía interesante analizar que carencias tienen las herramientas existentes antes de definir los objetivos, pero viendo que a lo mejor no estoy definiendo bien los objetivos si que me cuadra todo en un capítulo aparte.

2022-04-29 21:14 UTC, dipzza commented on doc/secciones/01_introduccion.tex
> +\textbf{Facilitar la asignación de tonos}. Al ser la parte que más tiempo consume y que requiere mayor nivel de habilidad reducir la complejidad de este proceso supondría un importante beneficio.
Ahora que le doy una vuelta creo que lo veo más como PMV tanto asignar los tonos como buscar los metadatos.

¿Como objetivo estaría bien "Crear una herramienta que permita automatizar / facilitar la creación de canciones para programas de karaoke en el formato estandar UltraStar .txt."?

Y tal vez como subobjetivo podría plantear que se pudiera usar en un tiempo razonable en ordenadores de gama media (¿debería definir el tiempo y dar un ordenador en concreto?)

2022-04-30 09:33 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\textbf{Facilitar la asignación de tonos}. Al ser la parte que más tiempo consume y que requiere mayor nivel de habilidad reducir la complejidad de este proceso supondría un importante beneficio.
El objetivo no debe ser tan concreto, y sobre todo no tener detalles de implementación. Yo cortaría en "canciones para programas de karaoke". Si quieres añadir programas competitivos, o "juegos", mejor. El tono no hace falta extraerlo si son simplemente programas de karaoke para cantar.

2022-05-13 15:39 UTC, JJ commented
> 1. _Closes_ don't work if included in the title.
> 
>     2. You need to say _why_ they close anything at all.

Still this...

2022-05-13 15:41 UTC, JJ approved these changes
OK, más o menos lo has arreglado todo. Si acaso surge alguna cosa más, más adelante. :+1:

2022-05-13 16:40 UTC, dipzza commented
Genial, añadí closes en el cuerpo más tarde, quito los que puse mal en el cuerpo y hago merge

2022-05-15 07:58 UTC, merged